export enum Discipline {
  BIOLOGY = 'BIOLOGY',
  CHEMISTRY = 'CHEMISTRY',
  COMPUTER_AND_DATA_SCIENCE = 'COMPUTER_AND_DATA_SCIENCE',
  MATHEMATICS = 'MATHEMATICS',
  PHYSICS = 'PHYSICS',
  ENGINEERING = 'ENGINEERING',
  EARTH_AND_ENVIRONMENTAL_SCIENCES = 'EARTH_AND_ENVIRONMENTAL_SCIENCES',
}
